### ISSUE TITLE
Prepare a file of existing strains

### ISSUE THREAD

**Issue by kimrutherford** [PHI-base/canto#16]
@CuzickA @martin2urban Alayne/Martin? Prepare a file of existing strains (a small test file with only a few lines will do in the first instance)

Moved from https://github.com/pombase/canto/issues/1347

Depends on: #15

**Comment by martin2urban** [comment]
We discussed in the meeting 15/1/18  that we would not use the ‘Pathogen_NCBI_**strain**_Taxonomy_IDs. This is because  NCBI are no longer assigning taxon ids to new strains. We will be using only NCBI Taxonomy species ID, species name (and perhaps synonyms). Strains will be provided as a pre-loaded list and the option of adding in NEW strain names as 'free text'.

**Comment by kimrutherford** [comment]
http://www.phi-base.org/images/pathogen_species_list.csv
http://www.phi-base.org/images/host_species_list.csv
