### ISSUE TITLE
WT gene with WT product level 

### ISSUE THREAD

**Issue by ValWood** [PHI-base/canto#7]
from
https://github.com/pombase/canto/issues/1359

PHI base need to be able to specify WT gene and product level  for some WT alleles when comparing strains.

@CuzickA  @hammond-kosack @KEHammond We already have the functionality to specify WT phenotypes in Canto  since your old implementation.  We needed this for dominant negative, or haploinsufficiency in a diploid etc where people  keep the WT copy and also have one mutant copy in the genome or over expressed etc.
So I forgot,  it is already available, just that PomBase do not use it on its own. This should work for you though?

![wt gene and product level](https://user-images.githubusercontent.com/7359272/32725260-489f6134-c86c-11e7-88cd-a9ace258cd2e.jpg)

When you get a local install working  can you check that this will work for all of your use cases, and then close.

**Comment by CuzickA** [comment]
Will test this once OBO files have been uploaded.

We particularly need this for the  'effectors'. https://github.com/PHI-base/PHI-base_ontologies/issues/7

We will want to record the WT genotype interaction phenotypes in the gene-for-gene interactions, before information from mutant allele phenotype is useful. Typically the pathogen avirulence (avr) gene is recognised by a corresponding host Resistance (R) in a strain specific manner to trigger host defence (such as Hypersensitive Response (HR) localised cell death which would kill a biotrophic pathogen)

**WT interactions** (NOTE: avr- could be caused by natural absence of gene in strain or naturally altered gene whose gene product is not recognised by the host R gene)
pathogen avr+ host R+ =incompatible/ resistant, no disease, resistance response (HR)
pathogen avr+ host R- =compatible/ susceptible, disease, no resistance response (no HR)
pathogen avr- host R+ =compatible/ susceptible, disease, no resistance response (no HR)
pathogen avr- host R- =compatible/ susceptible, disease, no resistance response (no HR)

**Mutant allele**
Take pathogen _avr- host R+ =compatible, disease, no resistance response (no HR)_
mutate few nt in avr- and change to avr+ which is now recognised by the host R gene and shifts the phenotype from susceptible to resistant

**Comment by Hammond-Kosack** [comment]
Please make sure NOT to send any more of this stuff to my private email

**Comment by ValWood** [comment]
see
https://github.com/pombase/canto/issues/1460
